### ISSUE TITLE
Libelec on Raspberry Pi 4

### ISSUE THREAD

**Issue by abrombo** [djp952/pvr.hdhomerundvr#116]
If I am running libelec on a raspberry pi 4 which distribution of hdhomerun should I use?

**Comment by djp952** [comment]
Sorry for the delay in response, LibreELEC is seemingly still using the 32-bit ARM kernel, I believe the "**linux-armhf**" distribution is the one that is likely still correct. If that one won't install, you should be able to revert to the lesser "**linux-armel**" dsitribution.

If neither of those work, please let me know, I've not been tested RPi4 LibreELEC for quite some time. I have the necessary hardware to do so available to me, I've just been working on other things for the past few months :)

**Comment by djp952** [comment]
I've opted to move this project into a "maintenance mode" as I am no longer spending the necessary time on it. I'm going to mark this as closed, but if you have trouble again please let me know, ok?
