### ISSUE TITLE
1.2.2 linux skip and ff/rw issue

### ISSUE THREAD

**Issue by ccaswell99** [djp952/pvr.hdhomerundvr#12]
Hi,
Let me say great work. 

But since the latest update the skip and fast forward / rewind has not worked well on my libreelec kodi 17.3 boxes. In both recorded content and paused live content the skip will only do 10 seconds even when it was press multiple times and shows on the screen it would be skipping more.  Fast forward seems to be only 2x even when 4x, 8x, 16x, or 32x are showing. The show time counts up quickly but when play is pressed it jumps back to a 2x time.

These were working well on the previous version.  If you need more information or can't recreate the issue I let me know.

**Comment by djp952** [comment]
Hmmm... that stuff all works OK for me, but I don't have LibreELEC set up anywhere at the moment.  What kind of hardware are you running, I'll see how close I can get to your setup and play around.

The "1.2" versions send all content (Live/Recorded) through a custom stream implementation to deal with Kodi not being able to handle certain channels via ffmpeg, and to prep for Kodi 18 "Leia" which does away with just passing Kodi a URL for content.  If there is a problem to solve, I'm sure it's in there -- that was hard to get "right", and it would appear it's still not quite there yet!

**Comment by ccaswell99** [comment]
I have two Amlogic S905X 2G RAM 8G ROM boxes. I'm running libreelec 8.1.3 and loaded the Linux armhf kryton 1.2.2.6423 zip.

**Comment by ccaswell99** [comment]
The 16.1 apk on a fire stick is working correctly.

**Comment by djp952** [comment]
armhf is definitely the right version for LibreELEC on that system (I downloaded and extracted the system image to make sure).  That's a very similar CPU to the Raspberry Pi 3, which I have, I will download LibreELEC and play around.  I also asked on the SiliconDust forums if anyone else is having similar problems to try and help narrow it down.

Just to confirm we are comparing apples to apples, the 1.1.x PVR client worked OK on LibreELEC 8.1.3 for you on the same hardware, right?  Would you be willing to reinstall 1.1.1 (https://github.com/djp952/pvr.hdhomerundvr/releases/tag/krypton-1.1.1) on one of the S905X systems to double-check that they behave differently while watching the same recorded TV show at the same time (Live TV may not share the exact same stream from the RECORD engine)?

**Comment by ccaswell99** [comment]
The last version I had run that was working correctly before the guide issues was 1.0.10. But I just tried 1.1.1 and it ff and skips fine.  I did a fresh download and install of 1.2.2 and it still seems to be acting strange, I tried to take a video but couldn't get a good picture. With 1.2.2 Watch the index time after pausing live tv, I see the number jump to current time after the first skip, but the skips seem the correct length. This seems different than I saw earlier, when the skips were not the correct length.

**Comment by djp952** [comment]
Hi ccaswell99, I wanted to let you know I haven't forgotten about you, I was away for about 2 weeks.  Catching up with things, this is on my list....

**Comment by djp952** [comment]
How about that I *did* forget about you (and everyone else).  I'll keep saying I'm sorry for a while.  I found a pretty big flaw in 1.2.2 that I have corrected in 1.2.4 regarding seek.  From the SD forums it looks like it's made progress for many, would you mind giving it a try if you're still around? 

What I had done in 1.2.2 was semi-ignore the position of the stream Kodi wanted when seeking, I had aligned everything to 188 byte MPEG-TS packet boundaries for the new packet filter.  This made Kodi unhappy in a number of ways.  While I never had the same amount of problems in testing as some folks had in real life, I was able to duplicate enough seek problems to narrow it down to this.

In 1.2.4, I no longer try to force Kodi to accept my will, I accept it's will again :)  It introduces a very small chance that one of the "bad" packets I'm filtering out may get missed, but I don't foresee that becoming an issue, it's much more likely it will never even be noticed.

So anyway, I think I found and fixed this, please let me know if you can!

**Comment by djp952** [comment]
General feedback for the seek changes in 1.2.4+ have been positive from the SiliconDust forums, I'll mark this one as closed.  Please let me know if you disagree.  Otherwise, thanks for taking the time to write this up, I really appreciate it!
