### ISSUE TITLE
Base Function Questions

### ISSUE THREAD

**Issue by W54J04S07T** [djp952/pvr.hdhomerundvr#125]
Ignore this if there are licensing issues... or complexity issues...

Is it possible to implement base functions similar to the free package SiliconDust issues for KODI and other packages?

Can some sort of EPG capabilities linked to other KODI EPG dedicated packages be used?  
How about record functions, again linked to other KODI addons ( kodi-pvr-iptvsimple, inputstream-ffmpegdirect,
etc... ) ?

Thoughts?

**Comment by djp952** [comment]
I'd like to maybe better understand the question?

SiliconDust used to provide a Script-based Addon for Kodi that they abandoned a while back, I think during Kodi 18 "Leia", but at the time it was functional and, generally speaking, obeyed SD's particular Design Language pretty well.

Team Kodi does have an HDHomeRun addon that implements a subset of what this addon provides but does not currently have any "HDHomeRun DVR" ecosystem capabilities.

As I understand it, Kodi has a long-standing desire to separate EPG from "PVR", but it has never been implemented. I have no insight into "Record" functions outside of you may be better served by a Kodi PVR addon that treats HDHomeRun devices as nothing more than an input source and does everything else on its own?

If I were you, I might look into "Plex"? :)

**Comment by W54J04S07T** [comment]
I guess what I'm looking for is to avoid things like Plex, DVR and TVheadend.  
Seems like using a sledgehammer to drive a pin with those apps.

It seems to me that HDHomerun_DVR is somewhat ( to put it mildly ) lighter than those
other apps and except for the fact that it seems to require a subscription to SD tools
could likely do much better with much less weight than ( for e.g. ) DVR or PLEX.
Certainly, KODI seems to already have EPG and recorder type modules that could 
potentially serve the purpose???

Or am I missing something here?

**Comment by W54J04S07T** [comment]
Understood.

Guess that means a sledgehammer named DVR... LOL

**Comment by djp952** [comment]
Agreed, and I truly hope this mentality someday comes to fruition in Kodi. I'll continue to do what I can to keep this working, but to that end there "is only so much I can do" without becoming reinvested in Kodi itself, which is a bridge I'm no longer willing to cross :(
