### ISSUE TITLE
New timer

### ISSUE THREAD

**Issue by catstitan** [djp952/pvr.hdhomerundvr#126]
When searching the guide  to add a "New timer" please don't make me have to delete the words "New timer" before I enter my search phrase. I am never going to search for "New  timer". Please make the default blank.

**Comment by djp952** [comment]
I wish I could :( This is a Kodi default when creating a timer outside of the EPG, like with Timers / Add Timer. The addon doesn't have a way to give that a different default value other than `New Timer`. Sorry!

**Comment by catstitan** [comment]
Ok.

I reported this on the Kodi repo. Hopefully they'll fix it. 

Thanks!
