### ISSUE TITLE
Kodi 17.4

### ISSUE THREAD

**Issue by Viper911** [djp952/pvr.hdhomerundvr#13]
I am running Kodi 17.4 on Windows 10x64. I just installed this addon. When I click on record or add timer I get an error and for me to check the logs. In my log I have. 

16:59:49.476 T:9240 ERROR: CPVRTimerType::CreateFromAttributes unable to resolve timer type (0x1, 0xa, 235985751)
16:59:49.712 T:9240 ERROR: AddOnLog: HDHomeRun DVR PVR Client: AddTimer failed due to an unhandled exception: constraint failed (1299)
16:59:49.712 T:9240 ERROR: PVR - PVR::CPVRClient::AddTimer - addon 'zuki.pvr.hdhomerundvr:my.hdhomerun.com' returned an error: the command failed
16:59:49.712 T:9240 ERROR: PVR - PVR::CPVRClients::AddTimer - cannot add timer to client '235985751': the command failed

May be a 17.4 change that is making this happen

**Comment by djp952** [comment]
Hi!  Sorry, I've been away on vacation and haven't tried 17.4 yet.  Looks like they killed the Android x86 version? (Completely unrelated, just saying - lol).

The only constraint on the database are "not null" clauses, so I'm guessing it's more of a problem with the backend, perhaps a change there or something bad happening in the code.  I'll have a look ASAP for ya.

Question - are you a DVR service subscriber? I've seen this before when the user isn't a subscriber and the backend services return no results; the code doesn't always handle that well, especially with timers (my fault - an error message would be much better than a blanket 'didn't work')

**Comment by Viper911** [comment]
I am not a DVR service subscriber.  I assumed that was only needed if you used the HDHR's DVR software/Plugin.  I was thinking Kodi was the one doing it and I didn't need it.  If that is a requirement then perhaps this wont work regardless of Kodi 17.4.  I do have Plex pass, so maybe I just need to do recording with that instead.

**Comment by djp952** [comment]
Yeah, this addon uses the same backend services that the SiliconDust application does, it just acts as a go-between for Kodi.  As far as I know there is currently no addon that does what you are looking for from the HDHomeRun devices natively, but I think it's being worked on :)  If Plex is an option that will probably suit your needs better.

I list an active DVR subscription as a requirement/prerequisite for the addon, is there something I can do to make that more clear? I feel bad you wasted your time like this.

**Comment by Viper911** [comment]
Naw, I must just have missed that.  I guess I can use the native plugin to watch live on Kodi for now and Plex Pass/MCEBuddy for recording.  I was hoping this would work as Plex I have to use the web client to schedule as their Kodi plug in doesn't let you do it nicely via via the guide.

**Comment by djp952** [comment]
That's surprising that the Plex addon doesn't work well in that regard. Sorry that you have to go through the hassle just to watch/record in that fashion.  Not to plug for SD or try to get you to spend money you don't need to, but have you considered opting into the DVR service?  If you have a system that can be always on to run the RECORD engine and can get around it's little scheduling quirks I've found it to be a pretty nice set up.  Even the family likes it better than Media Center at this point, and we lived and died on that platform for 8 years :)  Good luck my friend, I truly hope that a reasonable solution presents itself for you!

Marking this one as closed, but please don't hesitate to open a new Issue or drop me a line for anything I might be able to help with ...
