### ISSUE TITLE
Support for multiple HDHomeRun Prime tuners 

### ISSUE THREAD

**Issue by Andrew-Casner** [djp952/pvr.hdhomerundvr#19]
I currently have multiple HDHomeRun Prime's (4) but when I go to record more than three shows during the same time period it deletes the last recording  rule I created. I have 12 tuners available on my network yet it seems I can only access the tuner on one device.

**Comment by djp952** [comment]
Hi Andrew, unfortunately this PVR Client doesn't handle the actual recording functions, that is done by the HDHomeRun RECORD engine, so while I can't give you a definitive answer I can try to help you gather some information for SiliconDust.  Ultimately you will have to ask them why it's only using one of your Primes.

I can help you find out if SiliconDust's services know about all of your Prime tuners.  From a web browser, navigate to http://ipv4.my.hdhomerun.com/discover.  You should get back a text-based list of all your tuners and the RECORD engine.  Based on your description I would expect to see three tuners and one record engine.  For reference, I have two primes and one RECORD engine, here is what my result looks like (sanitized):

```
[
    {
        "DeviceID": "131EXXXX",
        "LocalIP": "192.168.0.XXX",
        "ConditionalAccess": 1,
        "BaseURL": "http://192.168.0.XXX:80",
        "DiscoverURL": "http://192.168.0.XXX:80/discover.json",
        "LineupURL": "http://192.168.0.XXX:80/lineup.json"
    },
    {
        "DeviceID": "131EXXXX",
        "LocalIP": "192.168.0.161",
        "ConditionalAccess": 1,
        "BaseURL": "http://192.168.0.XXX:80",
        "DiscoverURL": "http://192.168.0.XXX:80/discover.json",
        "LineupURL": "http://192.168.0.XXX:80/lineup.json"
    },
    {
        "StorageID": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX",
        "LocalIP": "192.168.0.XXX:XXXXX",
        "BaseURL": "http://192.168.0.XXX:XXXXX",
        "DiscoverURL": "http://192.168.0.XXX:XXXXX/discover.json",
        "StorageURL": "http://192.168.0.XXXX:XXXXX/recorded_files.json"
    }
]
```

If your results don't match what you'd expect, perhaps there is some reason that your other 2 Primes aren't talking to SiliconDust's servers, so the RECORD engine doesn't know they exist?  If you do see all your tuners here, I'd be at a loss as to why it's not using them, but again sadly it's out of my control or ability to do something about.

Armed with your discovery information (expected or unexpected), I suggest heading over to the SiliconDust forums (https://forum.silicondust.com/forum/), post a question for them.  I'd guess this would count as a "Software Troubleshooting" issue if you saw all your tuners in the list or "Hardware Troubleshooting" if you didn't. Be sure to include your three Prime DeviceID codes in your question, they will ask for that.  They are usually pretty quick to respond and they know their stuff.

Sorry I can't assist you directly, but hopefully this gives you a leg up in getting your problem resolved more quickly.  Good luck, and let me know how you make out!

**Comment by Andrew-Casner** [comment]
Thank you for your awesome response! I will head on over to their forums. Thanks for all the work you are doing on Zuki, it is a great add-on.

**Comment by djp952** [comment]
No worries, I hope they can help out.  Marking this one as closed, but please feel free to open a new issue (or reopen this if GitHub lets you do that).  Good luck my friend!!
