### ISSUE TITLE
Support for darwin (iOS) Kodi platforms

### ISSUE THREAD

**Issue by djp952** [djp952/pvr.hdhomerundvr#25]
There are still additional outstanding Apple-based Kodi platforms that could be supported by the PVR client:

**Krypton:**
darwin-ios
darwin-ios-arm64

**Leia:**
darwin-ios
darwin-ios-arm64
darwin-tvos

There appears to be no official Kodi builds for any darwin platforms earlier than Krypton, so Jarvis support isn't likely to be necessary.

**Comment by richardgetz** [comment]
So far I haven't been able to implement for tvOS. I will keep trying.

**Comment by djp952** [comment]
This just isn't going to happen, there is extremely little desire from the community and it would be another "extract and repack" job even if I had a way to build a compatible binary.  Leia got rid of Android APKs but added UWP APPXs -- "extract and repack" is a terrible way of doing things and I still have zero intention of getting an iPhone, so .. this issue is dead.  "Won't implement".
