### ISSUE TITLE
Leia PVR API 5.9.0

### ISSUE THREAD

**Issue by ssyspro** [djp952/pvr.hdhomerundvr#29]
Update Leia build for PVR API 5.9.0

**Comment by hunsra** [comment]
I second that.  Can't use the plugin in the latest nightly builds :-(

**Comment by KSears91** [comment]
I third that. I have been patiently waiting, but its killing me!

**Comment by djp952** [comment]
Sorry guys!  I'm getting back into this -- I had Leia updated to 5.10.1 but made a mistake trying to also update cURL and the Android tools at the same time and ultimately reverted it.  It looks like I can still use the old tools for Leia even though Kodi moved on a few versions.  It wasn't hard to just get it to work for 5.10.1, shouldn't take too long to do it again.  I'll have to dig into the new functionality they added to see what we can leverage, but just making it work isn't a big deal.  On it

**Comment by KSears91** [comment]
That is great news. I was forced to update a few days ago and lost your PVR. Thanks again.

**Comment by djp952** [comment]
https://github.com/djp952/pvr.hdhomerundvr/releases/tag/leia-1.2.9

It's clearly imperfect, much has changed in Leia since December.  The immediate problem I noted and wasn't able to resolve quickly is the reporting of real-time (live) streams.  Otherwise, it appears to be 'generally' functional :)

**Comment by KSears91** [comment]
Installed on odroid c2 with openelec. So far so good. Thanks again.
