### ISSUE TITLE
silicondust issue

### ISSUE THREAD

**Issue by ssyspro** [djp952/pvr.hdhomerundvr#32]
attn. djp952

! silicondust is trying to get in touch about a guide data download issue 

Please check in on the forums we the users love your work and want to continue using it.

"  by nickk » Thu Jun 21, 2018 5:20 pm

Has anyone heard from djp952?

(If the problem isn't resolved in the near future we will have to block this plugin from downloading guide until it is resolved).  "

**Comment by djp952** [comment]
Attention gotten. Will head over and have a look I hope it's not too serious!! Guess my Rip Van Winkle act didn't get us anywhere lol!

**Comment by djp952** [comment]
Changes made in version 1.2.9 and I PMed nickk.  He replied with a 'thanks' so I think they are satisfied with the tweaks.  Thank you so much for alerting me, I'm glad this didn't come to a head and force SD to lock the client out!!
