### ISSUE TITLE
local EPG data blank after update to zuki 1.311.6972

### ISSUE THREAD

**Issue by dawtyne10** [djp952/pvr.hdhomerundvr#50]
new to github, let me know if this is not the proper place to post my issue/question... I have read the "known issues" and wiki here.  also hours on google, hoping this is a simple mistake on my part...

I just updated to libreELEC 9.0 with Leia18 today with fresh install... along with zuki.pvr.hdhomerundvr-raspbian-armhf-leia-1.3.11.6972.zip

Currently my EPG data for local channels is completely blank, but premium hdhr channels display just fine.  Everything else is working as expected.

If i switch to the libreELEC "PVR HDHomeRun Client", local and premium guide data displays just fine.  I only lose the local EPG when using the zuki pvr.  

I have gone through all settings many times and recently set all back to default and still no bueno.  I have also tried clearing cached guide data to no avail. 

![image](https://user-images.githubusercontent.com/47284393/52169991-e9f5d500-2706-11e9-948e-80a3ac05a392.png)

I also checked my other libreELEC 8.2.5 install with kodi 17.6... when using zuki 1.39.6943, local and premium EPG works.  i updated to version 1.3.11.6972 and lose local epg data.  i revert back to zuki version 1.39.6943 and local epg data comes right back...  I do not have access to older zuki leia builds as just updated today.  Anything else I can try?

**Comment by djp952** [comment]
Yeah, I screwed up.  The new EPG code changes the channel number into an integer, which is stripping off the subchannels on you.

Working on a fix now.  I am so sorry for the hassle.  Thank you so much for the detailed information as well, it's truly appreciated!

**Comment by djp952** [comment]
The new '1.3.12' build has been released that should fix this for you. You will probably have to restart Kodi/libreelec after you install it for Kodi to load the missing data.  

Please let me know if you have any more difficulties, and I apologize again for the inconvenience I caused everyone here.

**Comment by dawtyne10** [comment]
Wow, you're amazing.  Thanks so much for the quick fix and response!   Absolutely no apologies necessary.   I have 4 different builds using your pvr script and use it every day... it was the least I could do to help out.

and, yes all epg issues seem resolved on kodi 17 & 18.  thanks again!

**Comment by djp952** [comment]
Fantastic! I'll flag this one as closed.  Please don't hesitate to open new issues or reopen old ones, always willing to do what I can.  Can't fix everything, but I come close! :)  Cheers!
