### ISSUE TITLE
Incompatibility with CoreELEC Kodi fork

### ISSUE THREAD

**Issue by djp952** [djp952/pvr.hdhomerundvr#52]
The PVR isn't compatible with CoreELEC (https://coreelec.org/).  CoreELEC made breaking changes to the Kodi PVR interface that were not accepted for inclusion into Kodi 18 "Leia".  They privately incremented the PVR API version to 5.10.4, but Kodi itself is still at version 5.10.3.

I had pinged CoreELEC briefly on their forums and asked if they would be willing to refactor their changes so that they could maintain compatibility with Kodi, but it didn't go anywhere.  Looking back through the history of the change, it appears even Team Kodi was also against the idea of an incompatible fork still being called "Kodi".

I respect and understand their need to make the change, even though I personally disagree with how they did it.  I am not in a position to build this PVR for all the various platforms I can support today and then also turn around and do it again for CoreELEC, especially since I don't have any devices capable of running CoreELEC.

That all said, there is a user on the SiliconDust forum thread for this PVR who goes by the name **timecutter** that has been rebuilding the PVR for CoreELEC.  I don't want to put this person on the spot here, that wouldn't be fair, but it may be worth watching the SiliconDust forum thread to see if/when s/he is able to produce these builds for the community.  (https://forum.silicondust.com/forum/viewtopic.php?f=88&t=65776&sid=985ca7bf332b96b99d49658f757dff36)

Update 2/8/19: To make matters worse, Team Kodi now has their own pending change that is being tagged as API 5.10.4 (https://github.com/xbmc/xbmc/pull/15467/files), which if they were to bring that into Leia, which they might since it's non-breaking in nature, CoreELEC and Kodi will now be in conflict.

**Comment by djp952** [comment]
Question asked by **edombroski** asked in another (closed) issue:

> Could you provide any guidance on hacking this to work on that platform? I'd be happy to get my hands dirty to try to hack this to work.  Any advice appreciated.

Actually, it shouldn't be that hard to roll your own, but I have a pretty unique build environment since I hit so many platforms at once.  It's Windows-based and all the tools are free, but it's many gigabytes and takes a while to set up.

That would be the easiest way, if the environment isn't too daunting to put in place.  If you can get the PVR to build using the directions in the README (https://github.com/djp952/pvr.hdhomerundvr) then it's should just a matter of replacing the formal Kodi code with CoreELEC's.  The Kodi code is kept as a 'submodule' named depends/xbmc.  If one were to apply all of CoreELEC's related patches on top of that, that would bump the PVR API to 5.10.4 automatically when you build.  I would have to review the patches to see if you'd need to change any actual PVR code, but if I recall you don't.  Things may have changed since last I looked, of course.

I'm happy to help get you set up, if you have the time and resources :) The README is quite comprehensive as to the environment, I think there is one SNAFU in there in that Java is needed for more than just Android (UWP needs it too) at this point, so make sure you install that even though it says it's "optional".

**Comment by scottpinkston** [comment]
The only changes needed are pvr.hdhomerundvr\depends\xbmc\xbmc\addons\kodi-addon-dev-kit\include\kodi\versions.h change the ADDON_INSTANCE_VERSION_PVR  "5.10.4" and then change pvr.hdhomerun\src\addon.xml.tt 	<import addon="kodi.binary.instance.pvr" version="5.10.4"/>.

the only other issue that I ran into was in msbuild.proj I changed gcc to arm-linux-gnueabihf-gcc-7.

**Comment by djp952** [comment]
I posted on the CoreELEC forums a suggestion to reuse a generally defunct field in the existing PVR channel structure for their purposes instead of changing the API.  It looks like they haven't hit "9.0.0" quite yet so there is a chance they will see it and perhaps agree to that or something similar.  That would be the best solution for third-party addons like mine.

I'm also working on a generic Makefile for the PVR for *nix systems to try and help with situations like this in the future.  Unfortunately all the build-time file generation is done in Windows (and I really like it the way it is - lol), so I also need to include something for that as well as creation of the .zip file (also done in Windows today).  But, the addon itself builds fine by just typing "make" :)

One other relevant point to this is that to truly build for CoreELEC as-is, you also should apply the following CoreELEC patches to the depends/xbmc tree before building (from CoreELEC/packages/mediacenter/kodi/patches):

kodi-ce-009-add-hasarchive-and-isplayable-listitem-apis.patch
kodi-ce-010-add-pvr-archive-support.patch

This will change the PVR_CHANNEL structure to match theirs and bump the API to 5.10.4.  My concern with not doing this is that their PVR_CHANNEL structure is bigger than it was, so without applying the patch the PVR will be sending in unexpected data.  At worst, if the PVR_CHANNEL happens to align to the end of a page you may get a segfault.  This is unlikely, however.  What definitely happens every time is that CoreELEC reads a Boolean value beyond the end of the structure, so it will end up as randomly true or false depending on what happened to be next in memory.

Short version: To recompile the PVR for CoreELEC using the existing build system, you should apply those 2 patches and change addon.xml.tt to say "5.10.4".  I'll see about changing that version to be a variable instead and eliminate that step too!

**Applying the CoreELEC patches**

This was tricky to get right because of Windows.  What I had to do was use WSL (Ubuntu 16.04LTS if you match my proposed build environment), go into the depends/xbmc folder and 'git checkout *' to replace all the CRLF line endings with LF line endings in the Kodi source tree.  Then I was able to successfully apply the patches.  Here is my command line history.  I had the patch files in D:\, and the PVR Leia branch in D:\git\Leia. The -p1 is required to normalize the patch paths against the current directory:

```
djp952@BREHMM-W10:/mnt/d/git/Leia/depends/xbmc$ git checkout *
djp952@BREHMM-W10:/mnt/d/git/Leia/depends/xbmc$ patch -p1 < /mnt/d/kodi-ce-009-add-hasarchive-and-isplayable-listitem-ap
is.patch
djp952@BREHMM-W10:/mnt/d/git/Leia/depends/xbmc$ patch -p1 < /mnt/d/kodi-ce-010-add-pvr-archive-support.patch
```

you can ignore the errors patch gives you about git binary diffs on ce-009, they are irrelevant for our purposes.  We only need the API changes.

Let's hope CoreELEC sees my post and agrees with it, then none of this matters! woot!

**Comment by djp952** [comment]
(Accidentally hit "Close and Comment" again - sorry). Reopened.

**Comment by djp952** [comment]
Great news - CoreELEC opted to go with my proposed solution (as-is, which I didn't expect).  9.0.0 was released already, but the changes were committed for whatever the next release is.

Here is a link if you want to drop them a thank-you.  I certainly did!

https://discourse.coreelec.org/t/rfi-pvr-api-5-10-4/2818

**Comment by djp952** [comment]
Marking issue as closed
