### ISSUE TITLE
Kodi 18.3 - unable to create timer

### ISSUE THREAD

**Issue by SupaFlav** [djp952/pvr.hdhomerundvr#57]
![65801946_882944525394505_7474579212121145344_n](https://user-images.githubusercontent.com/52390958/60406600-af447b80-9b84-11e9-8067-22aa0c99dbd7.jpg)

Error occurs after latest update to Kodi 18.3 / OSMC via Vero4k+.  Launching HDHomeRunSetup I was then prompted for update and firmware updated to version 20190621.  Restarted Kodi, but still not working.  HDHomeRun config states PVR service active and I was able to setup a recording/task via the Android HDHomeRun app.

I can still access live TV and my recordings without issue.  This error only occurs when attempting to setup a timer.

Thanks!

**Comment by djp952** [comment]
This is somewhat new to the PVR addon, it's going out to SD and checking your device identifiers to ensure that you have DVR service.  Since you do, clearly something is happening improperly there.

I will have a look here and make sure nothing has changed on the HDHomeRUn backend again on me.  Hang tight -- glad you have the Android SD app available to schedule things until we can get to the bottom of this one.

**Comment by SupaFlav** [comment]
Thank you Michael for your speedy response. If you require additional
details please let me know. Thanks! 😊

**Comment by djp952** [comment]
I didn't find anything wrong with the current code, but it occurred to me that I should have asked you what version of the PVR you are using? The API that I use to determine this changed a couple weeks ago and broke everybody.

I fixed that on 6/19/19 in version 2.0.4, but if you are on a release prior to that I suggest the latest v2.1.0.  v2.1.0 also allows Linux-based systems to auto-update now.  Except OSMC, but that's a different story altogether :)

If you are already on v2.0.4 or v2.1.0 let me know.  The next step would be to ask you to do a little groundwork in a web browser - it's not hard but involves some copy/paste action.  I intentionally don't log the magic codes from the tuner(s) anywhere that are used to check the account so it would be a few steps to go get them and then manually check the account API.

**Comment by SupaFlav** [comment]
Doh! I was running v2.0.2 and after updating to v2.1.0 everything works as expected.  Software 101 - make sure you're running the latest versions!  Sorry for inconviniencing you and thanks so much for your support!

**Comment by djp952** [comment]
No worries! I'm glad it turned out to be an easy fix. Be sure to let me know if you run into any other problems, ok? My pleasure to try and fix ya up!
