### ISSUE TITLE
Support for closed captions?

### ISSUE THREAD

**Issue by dp250f** [djp952/pvr.hdhomerundvr#63]
Are there plans for this plugin to support closed captions?

**Comment by djp952** [comment]
A PVR add-on isn't able to do anything about that specifically. The data stream from the tuner and/or RECORD engine is handed off to Kodi as-is, it's up to Kodi to determine if there are closed captions in that data.

Closed captions in and of themselves work fine for me; is there a more specific piece of information you can provide like a channel and/or program? Perhaps I can assist you with filing a Kodi issue if CC isn't working as expected?

I don't mean to just toss you over to Kodi but there is nothing specific I can do in the PVR add-on to deal with Closed captions. MPEG is MPEG, it's up to the decoder (Kodi) to know how to handle them

**Comment by dp250f** [comment]
Good to know. Plex took a long time to support closed captions - I guess we use a different subtitle system in the US than everywhere else. I'll look for how to get captions working in Kodi.

**Comment by dp250f** [comment]
So...  turns out it only works if you turn it on...  Thanks for all you do!
