### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by Yabdelwahed** [djp952/pvr.hdhomerundvr#67]
Hello,

I have been using the addon without issues for a couple of years. I have Kodi 18.6 and the HDHomeRun 3.5 version. The HDHR software is installed on a PC (Win10 64, automatically updated) that is on all the time and does the recording, it is UpToDate and when I turn it on I can see channels, guide for many days ahead and recorded software. If I try the HDHR plugin on my Amazon fireTV the same is true. I also have HDHR on a  different PC on the same LAN and can see guide, channels, and recording. 

The main PC where HDHR records to also happens to have my main Kodi installation and 3-4 weeks ago the guide disappeared, if I restart sometimes I see very brief message that say I don't have a valid subscription (although the HDHR website and app both say it is active). I also can't see any of the recordings (which makes me believe the plugin simply can't communicate and read the settings from the HDHR software).

I have tried my Kodi 18.6 installation on another PC also on the LAN and twith the 3.5 plugin and the TV, guide, recordings ETC all load without problems. 

On the PC with the issue if I go to the channels' list I can click and view any channel I want, but I can't pause or rewind/FF. So I am not sure if it has to do with read/write permission. I uninstalled and reinstalled the plugin, took ownership of the folder it is, removed any limitations on my windows use account settings (which is an administrator account). Kodi otherwise runs fine, I can watch shows, movies, pause, rewind etc. If I browse from it to the recording folder I can watch the shows that are saved without problems. If I activate the HDHR original add-on it would work without problems.

I have plenty of empty space, system CPU usage 4$, memory usage at 28%, and disk usage at only 46%.

I deleted the add-on, removed the folder and reinstalled, and updated multiple times without success, I tried to look into the kodi log and nothing stuck out.

Any suggested course of action would be appreciated.

Thank you

**Comment by djp952** [comment]
Hi! All the symptoms point to a problem with the addon being able to reliably discover the HDHomeRun device(s) on your network.  It uses the same method that the HDHomeRun app does by default, but there may be firewall rules or other things affecting how it might work from Kodi.

There may be a quick solution as the addon can also use the HDHomeRun cloud for discovery purposes.  If you go into Kodi / Addons / My addons / PVR Clients / HDHomeRun DVR PVR Client / Configure / Advanced, there is an option called "Use HTTP cloud-based device discovery".  Toggle that.

After changing that setting a discovery will execute immediately, but it won't necessarily refresh things like the EPG right away if it succeeds.  Suggest closing and restarting Kodi after changing that.

The way to know if this worked would be in the Kodi log file.  What you should be seeing is a set of entries that look like this, search on "discover_devices" to find them:

> 2020-05-20 09:16:59.303 T:6684  NOTICE: AddOnLog: HDHomeRun DVR PVR Client: discover_devices: initiated local network device discovery (method: broadcast)
> 2020-05-20 09:17:00.041 T:6684  NOTICE: AddOnLog: HDHomeRun DVR PVR Client: discover_devices: discovered: HDHomeRun PRIME 131ED0E0 (DVR authorized)
> 2020-05-20 09:17:00.041 T:6684  NOTICE: AddOnLog: HDHomeRun DVR PVR Client: discover_devices: discovered: HDHomeRun PRIME 131EB7F7 (DVR authorized)
> 2020-05-20 09:17:00.041 T:6684  NOTICE: AddOnLog: HDHomeRun DVR PVR Client: discover_devices: discovered: HDHomeRun RECORD E500A92F-F58F-F8CE-F5B8-2D10C224C933

These entries expose how the devices were discovered ["(method:broadcast)" means UDP broadcast, "(method:http)" means the cloud service.], what devices it found, and the DVR service authorization.

As for not being able to FF/RW, that means that it couldn't find or couldn't talk to your RECORD engine, which is what enables that functionality.  If it can't find RECORD it falls back to using a tuner on it's own, which disables the ability to timeshift the programming.

If switching the discovery method doesn't help, please let me know, we can examine what the cloud service thinks you have versus what you really have and go from there.

**Comment by djp952** [comment]
Hi @Yabdelwahed, any update on this?  Has the problem persisted?  I'm happy to help my friend!

**Comment by djp952** [comment]
It's been over a month with no additional info so I'll go ahead and mark this as closed.  

Please feel free (seriously) to reopen, add a new Issue, find me at the SiliconDust forum, or e-mail me at djp952 AT gmail DOT com if you are still running into problems (if e-mail please remind me about the problem, though, I get a lot of e-mail LOL).  

I honestly want to help you out if I can!  Thank you for using the addon and for reporting this Issue in the first place.  Can't provide solutions if I don't know the problems, right??
