### ISSUE TITLE
System is asking for license key.

### ISSUE THREAD

**Issue by gregwa1953** [djp952/pvr.hdhomerundvr#70]
I just purchased a new HDHomerun for our system to replace the existing one.

I was told by Silicondust support that My existing subscription, which expires in August 2021, would be fine.

I can't record anything nor can I get the full EPG.

Could you please let me know how to get it set up?

By the way, the new unit is the new Connect 4K ATSC 3.0 unit.  I was using a standard Connect 4 tuner before.

**Comment by djp952** [comment]
Hi!  Happy to help if I can, but this one seems to be more of a SiliconDust question/concern (The PVR addon in and of itself has no direct control over such things) ... Let's try to tackle them individually?

> I can't record anything

The ability to record is dependent upon an instance of the HDHomeRun RECORD service being installed and discoverable on your local network, as well as having an active HDHomeRun DVR subscription.  There are a number of things that can cause problems here, likely culprits being firewalls and subnets, but do you have a HDHomeRun RECORD instance running on your network? 

What I would request here is to see what your Kodi log says about device discovery from the addon.  When the addon starts up, it logs what it "found" on your network.  Here's mine:

```
2020-12-17 23:09:44.363 T:2776  NOTICE: AddOnLog: HDHomeRun DVR PVR Client: discover_devices: discovered: HDHomeRun PRIME 131ED0E0 (version: 20200907) (DVR authorized)
2020-12-17 23:09:44.363 T:2776  NOTICE: AddOnLog: HDHomeRun DVR PVR Client: discover_devices: discovered: HDHomeRun PRIME 131EB7F7 (version: 20200907) (DVR authorized)
2020-12-17 23:09:44.363 T:2776  NOTICE: AddOnLog: HDHomeRun DVR PVR Client: discover_devices: discovered: HDHomeRun RECORD E500A92F-F58F-F8CE-F5B8-2D10C224C933 (version: 20200907)

```

If there is no "RECORD" instance discovered or none of the tuner devices say "(DVR authorized)", the addon will enter a fallback mode that assumes you are not able to do such things.

> not can I get the full EPG

The ability to access EPG data via this addon was terminated by SiliconDust late last year **unless** you are a DVR service subscriber.  I have no control over this.  Using the above as the sample, unless you see at least one HDHomeRun device logged as "(DVR authorized)", you will not get any EPG data.

What I think you need to do is contact SiliconDust to get your new device associated with your existing DVR account, this is not something I can help you with as I'm not actually affiliated with SiliconDust in any way.

If you disagree with my assessment and feel that there is a defect/bug in the addon that is causing you problem(s), please do let me know and I will of course do whatever I can.  In this case, this unfortunately seems like it's between you and SiliconDust...

**Comment by gregwa1953** [comment]
You, as always, are correct.  It was a problem with my link with SiliconDust.  Thank you for your time.
