### ISSUE TITLE
HDHR Prime No EPG data | update_listings_task HTTP 500 

### ISSUE THREAD

**Issue by CatoA07** [djp952/pvr.hdhomerundvr#74]
Not receiving any EPG data from HDHomeRun Prime 3 as of the latest 20210210 firmware update. Checking the recent error messages shows "update_listings_task failed due to an exception: HTTP 500: Internal Server Error (1)

No such issue with the official HDHomeRun PVR client which is importing EPG data into Kodi with no issues. 

System info:
Nvidia SHIELD TV v2
Kodi 18.9 (updating to 19.0 is not an option at the moment as my skin has not finished adding support for it)
Zuki PVR version 3.4.1.7707 aarch64-leia
HDHomeRun Prime 3 (HDHR3-CC) Firmware Version: 20210210
HDHomeRun Record Version: 20210210

Attached are some screenshots as well that I hope may be helpful.
![IMG_0395](https://user-images.githubusercontent.com/52341592/108635764-cb2a1e80-7446-11eb-9a2f-a92c544df17c.jpeg)
![IMG_0397](https://user-images.githubusercontent.com/52341592/108635766-cd8c7880-7446-11eb-9dc7-400b7c97f5c4.jpeg)
<img width="541" alt="Screen Shot 2021-02-21 at 1 15 27 PM" src="https://user-images.githubusercontent.com/52341592/108635780-eac14700-7446-11eb-89b8-7080ee828532.png">
<img width="397" alt="Screen Shot 2021-02-21 at 1 15 40 PM" src="https://user-images.githubusercontent.com/52341592/108635782-eb59dd80-7446-11eb-9081-0a9dd8920b52.png">

**Comment by djp952** [comment]
There is an outage on the backend server, it's returning HTTP 500 for all requests.  Best we can do is wait for SiliconDust to resolve the issue.  Sorry :(

**Comment by CatoA07** [comment]
I see... Thanks for getting back.
Is there a status page where I can monitor this issue (or just some URL I can refresh occasionally from my browser to check on?)

**Comment by djp952** [comment]
Not that I am aware of.  I have been checking it occasionally since last night, and will reply here with any updates for ya.

All the other backend stuff is working and I posted on their forums, it's probably something simple like bouncing a service but being the weekend they may not be looking.

Kinda bad luck this happens to coincide with Kodi 19 release; lots of people are probably thinking the add-on broke :)

**Comment by djp952** [comment]
It's fixed!

**Comment by CatoA07** [comment]
Thanks for the update! I now know it didn't have anything to do with the add-on but I was messing with my whole network config and the HDHR + HDHR Record server before I opened the issue seeing if I could figure out where this webserver error was coming from so your quick response with clarification of the real cause was greatly appreciated.

Thank you so much for creating this project and paying so much attention to it! Please never stop working on it! I use it every single day, and other than this it has been flawless. I really, truly appreciate it.

**Comment by djp952** [comment]
You bet, it's my pleasure!  This is the first time this has happened, but I think some manner of notification is in order for this, it's quite a shock to realize you have to go to tvguide.com or something with no warnings!

I'll go ahead and mark this as closed, but please never hesitate to reach out here, on the forums, etc.  Always glad to lend a hand if I can or at least help figure out why things have gone to hell :)
