### ISSUE TITLE
Kodi 19.2 breaks hdhomerun pvr

### ISSUE THREAD

**Issue by abrombo** [djp952/pvr.hdhomerundvr#84]
Running ubuntu 20.04 tried to install zuki.pvr.hdhomerundvr-linux-x86_64-matrix-4.6.0.7908 on kodi 19.2 and got the error:
The dependance on kodi.binary.instance.pvr 7.1.0 could not be statisfied.  This worked with kodi 19.1.  Any suggestion?

**Comment by djp952** [comment]
While the VM is setting up; I bet you actually installed the latest nightly build, which is Nexus.  If that file has an "8.0.0" in it, that's what's going on.  I do have a Nexus API 8.0.0 compatible build if you need it.

While you're in Kodi, can you check what version it says it is in System Information?  Kodi 19.2 should say:

![Screenshot 2021-10-09 132951](https://user-images.githubusercontent.com/706055/136668521-ff2a8cb4-fad8-488b-b5de-19b65af46c24.png)

**Comment by djp952** [comment]
Hi @abrombo, any update on this?  If the problem does turn out to be that you have installed a Nexus version of Kodi I can provide you with a one-off build that will work.  I'm not planning on formally supporting Nexus quite yet, but it's not a big deal in any way.
