### ISSUE TITLE
Fire TV Cube

### ISSUE THREAD

**Issue by abrombo** [djp952/pvr.hdhomerundvr#87]
Is there a version of the hdhomerun pvr client that runs on a gen 2 Fire TV cube?

**Comment by djp952** [comment]
Should!  It appears the 2nd gen cube is a 32-bit operating system, so you'd want the **android-arm** variant.  Let me know if you run into any problems, once you get the .zip onto the machine in a place where Kodi can get to it, it should "just work"!

**Comment by djp952** [comment]
@abromo, any luck?

**Comment by djp952** [comment]
@abromo, I'm going to close this one out, OK?  Please don't hesitate to reopen or reach out for any additional concerns, OK?
