### ISSUE TITLE
timeshift no longer working after latest HDHomeRun release 20220128

### ISSUE THREAD

**Issue by SupaFlav** [djp952/pvr.hdhomerundvr#89]
Running OSMC/Vero4k Kodi 19.3 with zuki 4.7.0.  Issues presented after updating to HDHomeRun firmware to 20220125 / HDHomeRun Setup version 20220128 / software release 20220128.  Updated QNAP NAS for using latest DVR update but thereafter was unable to stream a recording "recording stream stream creation failed" (error popup on screen) or use any timeshift operations (no rewind/forward options visible on screen, nothing occurs using remote direction buttons).  Assuming timers no longer work as well.  Accessing the guide and streaming channels appears to be ok; however,  that typically doesn't require any of the DVR functions as it streams directly from the tuners.

Appreciate your work.  If there's anything I can gather for you, please let me know. Thanks!

FYI - I first encountered the fault installing 20220126 today and realised a new version was already present this evening, but still experiencing the same issues.  Re-installed the DVR driver on the NAS, restarted Kodi, no change.

**Comment by djp952** [comment]
Sorry I was away on vacation all this week :(  This is #2 in the queue to look into.  All kinds of things fell apart on us this week! LOL.

I'm back in town and catching up on the mayhem.

**Comment by SupaFlav** [comment]
You're taking vacation while my wife complains she can't timeshift her junk shows! How could you! 🤣

All good - thanks again!

**Comment by djp952** [comment]
I wasn't able to duplicate this concern after fixing the addon, but will continue to try.  I updated the DVR to the latest software as well and things still seem to work.

If you'd like, you are welcome to try out the test build for the main issues from last week:

https://1drv.ms/u/s!AgEGEEVzGNq-jLUShKj ... w?e=ptre3I

These are marked as "alpha1" but the feedback so far has been positive, so I may just push this out this evening and mop up any untested platform-specific issues with a follow-on release.  Note that installing an alpha/beta build does not break auto-update, once the non-alpha/beta goes out Kodi will update to that automatically.

Any feedback you can provide would be greatly appreciated!

**Comment by SupaFlav** [comment]
Heya, just loaded up 4.8.0 and all appears well now (timeshift & recording playback). Thanks so much for the speedy update!😄

**Comment by djp952** [comment]
Woohoo!  Will go ahead and close this one out, but PLEASE feel free to reopen or make a new Issue or anything if you run into additional problems, ok?  I fully expect there to be some type of fallout from this major of a change :)  Enjoy my friend!
