### ISSUE TITLE
Libreelec 9.2.8 no EPG

### ISSUE THREAD

**Issue by drl123** [djp952/pvr.hdhomerundvr#90]
Last week my Kodi boxes started complaining that I don't have a DVR subscription, but on my Win10 box, the HDHomeRun Setup says subscription is active.  I tried reinstalling Libreelec 9.2.8 on my RPI3 and install clean...it says it cannot find any tuners, yet the old SD card installation can find the tuners but no guides.  The channels play, but no guide data.

I tried repairing the Windows install...no change.  All firewall settings open.
I updated HDHomeRun on Windows...no change.
I installed HDHomeRun DVR on Mac...still can't see the DVR backend.

HDHomerun app works inside of Kodi, on Mac, Android...just can't use Zuki in Kodi.

Any suggestions for troubleshooting? (It's affecting all of my boxes).

Could this be related to the other issue you are working on for HTTPS on recordings?

**Comment by djp952** [comment]
Last week, HDHomeRun abruptly changed all their backend services to require HTTPS with TLS v1.2, which the addon didn't have.  I was also on vacation at the time :)  I'm working to rectify this as fast as I can and actually expect to have a test build later tonight.  The Nexus branch is building as I write this and if successful I'll start backporting the changes to Matrix and Leia.

Oh I didn't read the whole thing - lol.  Yes, it's all related.  The call to get your account information, which enables access to EPG data was also changed to require TLS :(

Hang tight, working as fast as I can for ya; will link to the test builds when they are ready. I can use all the help I can get to make sure as many platforms work again as possible before releasing it!

**Comment by drl123** [comment]
Thanks.  I thought it might be related, but that issue was on a different platform and just wanted to be sure.  If I can be of any help testing the fix, just let me know.  I have a couple RPI3's and one Rock64 all running Leia, but I have an SD card ready to go for the Rock64 with Matrix.

**Comment by djp952** [comment]
Hi!  I have test builds available that should fix everything: https://onedrive.live.com/?authkey=%21AISo7jpF%5FU1t9mc&id=BEDA187345100601%21203410&cid=BEDA187345100601

These are marked as "alpha1" but the feedback so far has been positive, so I may just push this out this evening and mop up any untested platform-specific issues with a follow-on release.  Note that installing an alpha/beta build does not break auto-update, once the non-alpha/beta goes out Kodi will update to that automatically.

Any feedback you can provide would be greatly appreciated!

**Comment by drl123** [comment]
Awesome!  I'll try it out over lunch, or after work today.

**Comment by djp952** [comment]
Woot woot!  Since it was "released" I'll mark this as closed.  PLEASE feel free to reopen or create new Issues for anything you run into, ok?  Sorry again for the protracted outage :(
